### ISSUE TITLE
require json is not working

### ISSUE THREAD

**Issue by algiuxass** [neonious/lowjs#114]
Example from avj node module:
```js
var metaSchema = require('./refs/json-schema-draft-07.json');
```
```
TypeError: cannot resolve module './refs/json-schema-draft-07.json', parent '..../node_modules/ajv/lib/definition_schema.js'
```

Make it possible to require json files.

**Comment by neoniousTR** [comment]
low.js should support requiring JSON files. I will try myself next weekend and report!

**Comment by neoniousTR** [comment]
Requiring JSON files works perfectly. I guess the problem is the "..../" instead of a "../../", so the resolving has some kind of bug. Do you have an example project or steps to do to trigger such an error?

**Comment by algiuxass** [comment]
Sorry, forgot to mention the "...." was to hide full path or whatever was it. It's shouldn't be a problem now. Thanks!
