### ISSUE TITLE
Missing 'global.require' (undefined)

### ISSUE THREAD

**Issue by algj** [neonious/lowjs#115]
I wanted to replace `require` function to accept json files, but I noticed that `global.require` is undefined, but functions like `global.console.log` aren't, this is weird.

Same for `Module.prototype.require`, `Module` is undefined.

How do I replace `require` function?

**Comment by neoniousTR** [comment]
require is currently defined per module.

But if you simply want to require JSON files, let me check what the problem with #114 (require JSON files) is this weekend and report!
