### ISSUE TITLE
would espressif wrover with 2mb psram work?

### ISSUE THREAD

**Issue by dkebler** [neonious/lowjs#119]
Espressif has an new flavor of wrover (saola) but it only has 2mb psram.  Is this sufficient for lowjs?

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/hw-reference/esp32s2/user-guide-saola-1-v1.2.html
https://www.amazon.com/gp/product/B087T7HWFQ/ref=ask_ql_qh_dp_hza

**Comment by ThomasRogg** [comment]
Hi! low.js actually only needs 1 MB. But we only let it run on 4 MB PSRAM because the user experience would really not be great with 2 MB. Too often at the limit.
