### ISSUE TITLE
use IO-plugin APIs for  GPIO

### ISSUE THREAD

**Issue by monteslu** [neonious/lowjs#12]
If the gpio support was shaped like the johnny-five IO APIs you'd get a lot of extensions for free.  Aside from direct johnny-five access, you'd be able to support libraries like:

https://github.com/louiemontes/node-led
https://github.com/noopkat/oled-js
and https://github.com/ajfisher/node-pixel

**Comment by gitowiec** [comment]
So how gpio support is shaped then? Where I could read about it? I'm looking into lowjs because I would like to flash some colorful LED stripes with my Pi Zero W using REST Api written in JS...

**Comment by janus** [comment]
> So how gpio support is shaped then? Where I could read about it? I'm looking into lowjs because I would like to flash some colorful LED stripes with my Pi Zero W using REST Api written in JS...

@gitowiec  Please why REST API for just LED stripes? If all you want PI Zero for is to do LED thingy then check this link, https://github.com/Mikestylz/CirnOS

**Comment by gitowiec** [comment]
@janus Thanks for your replay, but:
1) I don't know Lua
2) I know JS
3) I don't want to resign from using Raspbian (I don't want to lock my Pi Zero from other features by closing it with CirnOS installation)
4) REST Api is just a step for another application from another device to control the LEDs

**Comment by ryanjgill** [comment]
@gitowiec You can use the [FadeCandy ](https://www.amazon.com/Adafruit-FadeCandy-Dithering-USB-Controlled-NeoPixels/dp/B00JHJJF9W/ref=sr_1_1?keywords=fadecandy&link_code=qs&qid=1550847980&s=gateway&sr=8-1&tag=wwwcanoniccom-20)board with a pi zero and drive it using nodejs with [node-fadecandy](https://www.npmjs.com/package/node-fadecandy) module. 

I used them in this project [NeoPixel Clock](https://www.hackster.io/ryanjgill2/neopixel-clock-d3a262) and its working great.
