### ISSUE TITLE
low.js dead ?

### ISSUE THREAD

**Issue by bereldhuin** [neonious/lowjs#143]
Hi,

Is this project still alive ? 

It seems really interesting but no code has been updated since 1 year and the lowjs.org website is dead (expired certificate since 6 months).

Regards,

Fred

**Comment by ThomasRogg** [comment]
Hi!
The project is in "hibernation mode". My priorities have shifted so I cannot spend time on it for open source/hobbyists. Not sure what place low.js will have in the future.
Regards,
Thomas
