### ISSUE TITLE
Documentation: Babel configuration?

### ISSUE THREAD

**Issue by lll000111** [neonious/lowjs#15]
I would like to know from somewhere what Babel settings are required. It does not seem to be completely straightforward, with some features supported natively but most not.

List of "post ES5" features I woudl not need to Babel: https://wiki.duktape.org/PostEs5Features.html

So... this looks like a complex Babel setup. I think there should really be an example. Since the IDE does transpilation, what does it use?

Assuming people using Babel 7 and ES 2017; the new Babel version because it was such a big and long-planned step from Babel 6, and ES 2017 because downgrading is easy.

**Comment by lll000111** [comment]
UPDATE

I found https://www.neonious.com/Documentation/lowrmt

> By default, all JavaScript files synced to the device will be compiled down to EcmaScript 5, so you may use many modern EcmaScript features transparently with the device.

Okay, so whenever I sent files to the device the transpilation is automatic. Still, I would be curious about the configuration - I would like to test the transpiled code on the PC where the mocha tests run. (How would I run mocha tests on the device?)

**Comment by neoniousTR** [comment]
It's easy. You just use babel-preset-env without any additional configuration.

Not sure about Flow type-annotated code. Do you have an example file?

**Comment by lll000111** [comment]
https://babeljs.io/docs/en/babel-preset-flow

Doesn't that transpile "too much"`? I mean things that DuckTape could actually do natively.
