### ISSUE TITLE
Why using index 0 when matching with index 1

### ISSUE THREAD

**Issue by janus** [neonious/lowjs#21]
In the second  IF ELSE statement  why using  
`LowDataCallback *elem = low->data_callback_first[0];`  instead of  
`LowDataCallback *elem = low->data_callback_first[1];`

`void low_data_clear_callback(low_main_t *low, LowDataCallback *callback)`
`{`
    `pthread_mutex_lock(&low->data_thread_mutex);`
    `if(low->data_callback_first[0] == callback)`
    `{`
        `LowDataCallback *elem = low->data_callback_first[0];`
        `low->data_callback_first[0] = elem->mNext;`
        `if(!low->data_callback_first[0])`
            `low->data_callback_last[0] = NULL;`
    `}`
    `else if(low->data_callback_first[1] == callback)`
    `{`
        `LowDataCallback *elem = low->data_callback_first[0];`
       ` low->data_callback_first[1] = elem->mNext;`
        `if(!low->data_callback_first[1])`
           ` low->data_callback_last[1] = NULL;`
`}`

**Comment by neoniousTR** [comment]
Thank you, great job finding this, fixing it right away!
