### ISSUE TITLE
Unexpected behavior while play with low_add_stash

### ISSUE THREAD

**Issue by janus** [neonious/lowjs#22]
Noticed that is  one includes PRINTF statement inside the below function, it becomes extremely hard f for one to use repl, ie JS at the console. Is this a bug or that is the effect of threads?

int low_add_stash(low_main_t *low, int index)
{
    if(low->duk_flag_stop)
        return 0;

    duk_context *ctx = low->stash_ctx;
    if(duk_is_undefined(ctx, index))
        return 0;

    duk_push_global_stash(ctx);
    duk_get_prop_string(ctx, -1, "low");
 //printf("%d", index);
    int stashIndex;
    while(true)
    {
        stashIndex = ++low->last_stash_index;
        if(!stashIndex)
            stashIndex = ++low->last_stash_index;

        if(!duk_get_prop_index(ctx, -1, stashIndex))
        {
            duk_pop(ctx);
            break;
        }
        duk_pop(ctx);
    }

    duk_dup(ctx, index);
    duk_put_prop_index(ctx, -2, stashIndex);
    duk_pop_2(ctx);

    return stashIndex;
}

**Comment by neoniousTR** [comment]
This is not unexpected. low_add_stash is simply used very often, for example with every setTimeout or setInterval.
