### ISSUE TITLE
Cannot create Github issue

### ISSUE THREAD

**Issue by lll000111** [neonious/lowjs#26]
I tried creating an issue and it seemed to work twice, got nr. 24 and 25 respectively after submitting the new issue, but a second later the issues list did not show my new issue and when I reloaded the page I had just received after opening the new issue I got code 404 from Github - it had just disappeared....?

**Comment by styfle** [comment]
Try reporting GitHub issues to https://github.com/support

**Comment by styfle** [comment]
The issues you made are #24 and #25

**Comment by lll000111** [comment]
This issue was a test, since the others did not go through I did not expect this one either. Github support said they had issues earlier. Glad to see the issues were not actually lost.
