### ISSUE TITLE
crypto: SHA-256 hashes in hex notation are not always 64 characters

### ISSUE THREAD

**Issue by lll000111** [neonious/lowjs#33]
Using low.js for Linux, downloaded 9 December, 2018: https://www.lowjs.org/downloads/lowjs-linux-x86_64-20181209.tar.gz

Apparently hex values like "0a" are written into the final SHA-256 hash as just "a" when the hash string is created from its components.

```
> mha@mint-virtual-machine ~/neo $ node
> const crypto = require('crypto')
undefined
> crypto.createHash('sha256').update("strin", 'utf8').digest('hex').length
64
> crypto.createHash('sha256').update("strin", 'utf8').digest('hex')
'98db433e68d56413cb026680937df70118070c105d0c8a74f4b6f8ec5ea140ee'
```

vs.

```
> var crypto = require('crypto')
undefined
> crypto.createHash('sha256').update("strin", 'utf8').digest('hex').length
62
> crypto.createHash('sha256').update("strin", 'utf8').digest('hex')
'98db433e68d56413cb026680937df7011807c105dc8a74f4b6f8ec5ea140ee'
```

For direct comparison, the missing "0"s shown as spaces:

```
98db433e68d56413cb026680937df70118070c105d0c8a74f4b6f8ec5ea140ee
98db433e68d56413cb026680937df7011807 c105d c8a74f4b6f8ec5ea140ee
```

 <br>

PS: On the new https://www.lowjs.org/ I cannot find the Github link any more. EDIT: Ah okay, under Downloads. I think this should be a on the top of the page, many projects have it as part of the page header on all pages, to clearly show that it is open source.

**Comment by neoniousTR** [comment]
fixed in git, will be in download version tomorrow morning
will create new package for esp32 + neonious when at least one other commit is fixed tomorrow night.

**Comment by neoniousTR** [comment]
BTW: thank you for the tip with the github link. we will add that
