### ISSUE TITLE
node.js compatibility: things I miss in the "fs" module

### ISSUE THREAD

**Issue by lll000111** [neonious/lowjs#34]
There is an object with constants on `require('fs').constants` in node.js

https://nodejs.org/api/fs.html#fs_fs_constants_1

I'm using them in fs method calls, for example `fs.access(file, fs.constants.F_OK, function (err) {...`

Other node.js `fs` functions I use that are missing in low.js:

- `fs.constants` (I only use `F_OK` and only with `fs.access`)
- `fs.access()` (only for checking file existence, see the note at the end)
- `fs.readdir()`
- `fs.appendFile()` (JS-code convenience function in node.js using `fs.writeFile`)
- `fs.mkdir()`

I can replace my file existence check, which uses `fs.access` and `fs.constants` with an attempt to `fs.read`. I think `readdir` and `mkdir` might not be too complicated to add? I can of course [replace `fs.append` by `fs.writeFile` with an "append" option](https://github.com/nodejs/node/blob/v0.11.4-release/lib/fs.js#L970) since its only in the node.js API for convenience (I hope low.js supports the "append" flag).

**So the only ones I don't have a workaround for are `readdir` and `mkdir`.**

I use `fs.access` to check existence (without doing anything else to the file, really just a pure existence check) because node.js docs say so: https://nodejs.org/dist/latest-v11.x/docs/api/fs.html#fs_fs_stat_path_options_callback

> To check if a file exists without manipulating it afterwards, fs.access() is recommended.

**Comment by neoniousTR** [comment]
This will be done Tuesday morning - so my current plan.

**Comment by neoniousTR** [comment]
done :-)
