### ISSUE TITLE
Type issue with wifi password

### ISSUE THREAD

**Issue by bart** [neonious/lowjs#46]
When I try to set the wifi mode to `station` and pass a wifi password like `wifi.password="11112222333344445555"` I'm getting back an error saying that the given value (integer) is not valid for this setting. So I'm passing a string but it looks like internally its converted to integer which is a problem. Most FritzBoxes for example use a string of numbers as password.

Is it a problem in lowjs or the underlying system?

Thanks a lot!

**Comment by neoniousTR** [comment]
Looks like a problem in lowsync.. Thank you for the info! Giving this to a team member.

**Comment by neoniousTR** [comment]
Can you try out with the new lowsync version in npm?

**Comment by bart** [comment]
I think it still has an issue:

`lowsync settings set wifi.dhcp="client" wifi.mode="station" wifi.password="<just numbers OR a string>" wifi.ssid="<MySSID>" wifi.static_gw="192.168.178.1" wifi.static_ip="192.168.178.99"`

Error I'm getting, even if I use a string or string that just contains numbers:
A password was not set for the microcontroller. Please set a password via the lowsync settings set command.

**Comment by neoniousTR** [comment]
This is just a security advise. The settings should have been set anyhow.
Please tell if I we should continue looking. Closing for now.

**Comment by neoniousTR** [comment]
Whoops... Actually there was a problem making this now work. But is is not the advise.
Will be fixed tomorrow with new lowsync version.

**Comment by neoniousTR** [comment]
Fixed in new lowsync version, update for fix please.
