### ISSUE TITLE
Feature: function.toString()

### ISSUE THREAD

**Issue by lll000111** [neonious/lowjs#49]
We are actually using the `toString()` method on functions to get the source code of functions. On low.js I always get

    'function myFunction() { [ecmascript code] }'

*EDIT:*

Just FYI, I can work around this, in fact I may remove our option to store function code entirely. Still, [**that's what current JS spec wants, ES 2015+**](https://tc39.github.io/Function-prototype-toString-revision/) so I'll leave this for the backlog queue.

**Comment by neoniousTR** [comment]
Well, people did not think about embedded when they wrote that. Keeping the full code in memory would be bad, and thus I do not think I would like to implement this.

**Comment by lll000111** [comment]
Okay.
