### ISSUE TITLE
Will this run on a Samsung Artik 5x SOC?

### ISSUE THREAD

**Issue by mateodelnorte** [neonious/lowjs#5]
Hi there,

Neat project. Will it run on a [Samsung Artik 5x SOC](https://www.artik.io/modules/artik-530/)? 

Thanks.

**Comment by neoniousTR** [comment]
If the SOC is running Linux, yes.

**Comment by neoniousTR** [comment]
Just took a second look, to see if it makes sense to go more low level, as we are doing it with low.js for ESP32, where Linux is not used.

That SoC is expensive. 100x on Mouser still cost 37 € per piece. Wow.

Is there a reason why you are looking at this particular SoC?

**Comment by neoniousTR** [comment]
No comment => Close
