### ISSUE TITLE
KE32-WROVER can't connect to the the default gateway on the wifi.

### ISSUE THREAD

**Issue by DeaSTL** [neonious/lowjs#53]
![image](https://user-images.githubusercontent.com/19532324/54007482-fdde8d80-412f-11e9-8156-be894001180b.png)

**Comment by neoniousTR** [comment]
Hello! I am not sure what you are trying to say. It looks like your local web browser cannot connect to 192.168.0.1. But what is 192.168.0.1 supposed to be? I need some more information. Thank you!

**Comment by DeaSTL** [comment]
@neoniousTR  I've flashed the firmware to my esp32 Wrover and then connected to the wifi provided by the esp32-wrover and once i've entered the ip provided by the dialog in lowsync, it instantly disconnects.

**Comment by neoniousTR** [comment]
I am sorry, but I do not understand your description. What disconnects? The Wifi? I cannot reproduce this. And what does that have to do with the screenshot? I cannot see that anything disconnects in the screenshot?
