### ISSUE TITLE
Missing polyfill for Array.prototype.fill

### ISSUE THREAD

**Issue by Nervengift** [neonious/lowjs#56]
Using the IDE I can't use Array.prototype.fill [1] in js files

`TypeError: undefined not callable (property 'fill' of [object Array])`

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

**Comment by neoniousTR** [comment]
This is ES2015. I will add the polyfill in the next 2 weeks.
