### ISSUE TITLE
Now with TypeScript: but lots and lots of errors

### ISSUE THREAD

**Issue by lll000111** [neonious/lowjs#59]
Now we actually switched to TypeScript, so I thought since your IDE is focused on it we should have smoother sailing. I was wrong :(

I updated the Neo One's firmware. I prepared the TS files and then uploaded them into /src on the Neo One, to continue with the IDE from there. Structure: index.ts in /src/ and a directory /src/one.core (plus, below, ./sytem/ and ./util/) with a lot of module files, all .ts.

After uploading I started the IDE and it started to compile the .ts files. Result: Lots and lots of errors for almost everything that I thought would be normal. Even basic TS types like Promise, Map, Set are unknown, but also others like `Property 'from' does not exist on type 'ArrayConstructor`. The only imports that work are from index.ts to two one.core/ files, all relative imports inside that directory fail. The path I use (in /src/one.core/) is `./storage-base-common`, for example, the error message then refers to `file:///one.core/storage-base-common`

Output: https://2c2ba923-f87a-4112-8b33-4a621bcc8260.htmlpasta.com/

Also, using TypeScript 3.4.5, I have no errors when I check the source code. The IDE shows a few, e.g.  `This condition will always return 'false' since the types 'T' and 'number' have no overlap.(329, 9)`.

Seems like at the very least the target for TS transpilation is not set to ES2015 or above (my setting is "esnext").

**Test code archive sent by email.**

Screenshot of some of the errors &mdash; click on it for a better view:

![Unbenannt-1](https://user-images.githubusercontent.com/25476357/57011573-99f1b600-6c02-11e9-90bb-a7c4a8c7350a.png)

**Comment by lll000111** [comment]
By the way, before uploading the .ts files I tried uploading the .js files created by my development environment's TypeScript transpiler.

The result: After the sync was done, 100% CPU for a minute, then "connection was lost" (both lowsync monitor and IDE), after a reconnect (automatic for lowsync monitor, manual restart of IDE) I saw - nothing. The code didn't produce the files it was supposed to.

The same very simple "only start the app and let it create its default files" had already worked a while ago, when I had issues with heap and cache sizes). So this is a step backwards.

**Comment by lll000111** [comment]
PS: I compile with `tsc` for

```
"importHelpers": true,
"esModuleInterop": true,
"module": "CommonJS",
"moduleResolution": "node",
"target" "es5", 
"lib": ["esnext", "dom"],
```

and all I need is the (small) `tslib.js` imported by some files.

**Comment by neoniousTR** [comment]
We have to decided to remove TypeScript from the official support list. Just not enough people who request it, and so we need to concentrate on other things. See https://www.neonious.com/documentation/changelog on what we are doing.

This changes however as soon as someone is willing to sponsor TypeScript development. Till then, I am closing this issue.

**Comment by lll000111** [comment]
That's a good thing, I argued against it from the start if you remember :-)
