### ISSUE TITLE
set wifi params on flash esp32

### ISSUE THREAD

**Issue by fdjean** [neonious/lowjs#61]
Hi,
My desktop machine do not have wifi, 
how I can update the esp32 as client to use my wifi router (ssid, password ..) ? 

something like that will be good:
`
lowsync flash /dev/cu.SLAB_USBtoUART --init --config=./conf.json
`
thx

**Comment by neoniousTR** [comment]
Hello,
sorry, currently only possible through the Wifi AP, instructions see here: https://www.lowjs.org/documentation/flash-space.html
You might want to take a look at the neonious one which has Ethernet:
https://www.neonious.com/neoniousOne
Regards,
Thomas

(will close in a few days, as not a bug)
