### ISSUE TITLE
Any chance to run node-red by low js?

### ISSUE THREAD

**Issue by podarok** [neonious/lowjs#64]
topic

**Comment by neoniousTR** [comment]
We provide an environment just like Arduino and other developers can develop programs for it. That is what we do. We are not affiliated with Node RED.

So you have to ask the node-red guys. Have you done that already?

**Comment by podarok** [comment]
Hi @neoniousTR 
Thank you for the response
I thought somebody from low js team is aware about some of best nodejs embedded solutions that could be run by lowjs
I tries - it doesn't work - a lot of dependencies needed.
Looks like node-red is to much for the system like esp32
