### ISSUE TITLE
m5stack

### ISSUE THREAD

**Issue by 0x77dev** [neonious/lowjs#84]
m5stack support?

**Comment by neoniousTR** [comment]
Depends on whether it uses the ESP32-WROVER or external 4 MB PSRAM.

Just checked: The M5Camera does. The other boards, I do not think so.

**Comment by 0x77dev** [comment]
I have m5stack Core, I will test it out, maybe we can write some lib for m5stack?

**Comment by neoniousTR** [comment]
Try it, but I really think m5stack Core does not have the PSRAM.

**Comment by 0x77dev** [comment]
Its works^ but... after 5seconds it crashes and goes to infinity reboot.

**Comment by neoniousTR** [comment]
I think it does not have the PSRAM. Am I correct?

**Comment by tobozo** [comment]
M5Stack-Fire has psram, same for Odroid-Go.

**Comment by airtonix** [comment]
m5paper has psram too. 

![external-content duckduckgo com](https://user-images.githubusercontent.com/61225/108774648-d6e52480-75af-11eb-867a-9f4ac094ead6.jpg)
